apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shoehorn.fullname" . }}-cerbos
  namespace: {{ include "shoehorn.namespace.backend" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
    app.kubernetes.io/component: cerbos
spec:
  replicas: {{ .Values.cerbos.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "shoehorn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cerbos
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-cerbos.yaml") . | sha256sum }}
      labels:
        {{- include "shoehorn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cerbos
    spec:
      {{- include "shoehorn.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "shoehorn.serviceAccountName" . }}
      securityContext:
        {{- mustToYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: cerbos
        securityContext:
          {{- mustToYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.cerbos.image.repository }}:{{ .Values.cerbos.image.tag }}"
        imagePullPolicy: {{ .Values.cerbos.image.pullPolicy | default "IfNotPresent" }}
        args:
          - "server"
          - "--config=/config/config.yaml"
        ports:
        - name: http
          containerPort: 3592
          protocol: TCP
        - name: grpc
          containerPort: 3593
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: audit
          mountPath: /tmp/cerbos-audit
        {{- include "shoehorn.grpcMtlsVolumeMounts" . | nindent 8 }}
        livenessProbe:
          httpGet:
            path: /_cerbos/health
            port: http
            {{- if .Values.global.mtls.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cerbos/health
            port: http
            {{- if .Values.global.mtls.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- mustToYaml .Values.cerbos.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "shoehorn.fullname" . }}-cerbos-config
      - name: audit
        emptyDir: {}
      {{- include "shoehorn.grpcMtlsVolumes" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- mustToYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- mustToYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- mustToYaml . | nindent 8 }}
      {{- end }}
