apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shoehorn.fullname" . }}-web
  namespace: {{ include "shoehorn.namespace.frontend" . }}
  labels:
    {{- include "shoehorn.web.labels" . | nindent 4 }}
  annotations:
    {{- include "shoehorn.serviceAnnotations" .Values.web.annotations | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.web }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shoehorn.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "shoehorn.serviceAnnotations" .Values.web.annotations | nindent 8 }}
      labels:
        {{- include "shoehorn.web.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "shoehorn.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "shoehorn.serviceAccountName" . }}
      securityContext:
        fsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: web
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
        image: {{ include "shoehorn.componentImage" (dict "component" .Values.web "Values" .Values) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 4173
          protocol: TCP
        env:
        - name: VITE_ENVIRONMENT
          value: {{ .Values.web.env.VITE_ENVIRONMENT }}
        - name: VITE_API_URL
          value: "/api/v1"
        - name: VITE_DOMAIN
          value: {{ .Values.global.domain }}
        livenessProbe:
          {{- toYaml .Values.web.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.web.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.web.resources | nindent 12 }}
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-tmp
          mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: nginx-cache
        emptyDir:
          sizeLimit: 10Mi
      - name: nginx-run
        emptyDir:
          sizeLimit: 1Mi
      - name: nginx-tmp
        emptyDir:
          sizeLimit: 1Mi
