{{- if .Values.registryCredentials.enabled }}
{{- range .Values.registryCredentials.registries }}
{{- if and .username .password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shoehorn.fullname" $ }}-registry-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "shoehorn.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.registryCredentials.existingDockerConfigJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shoehorn.fullname" . }}-dockerconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryCredentials.existingDockerConfigJson | b64enc }}
{{- end }}
