{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shoehorn.serviceAccountName" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- mustToYaml . | nindent 4 }}
  {{- end }}
{{- end }}
