{{- if and .Values.valkey.enabled (not .Values.valkey.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoehorn.fullname" . }}-valkey
  namespace: {{ include "shoehorn.namespace.data" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: valkey
      protocol: TCP
      name: valkey
  selector:
    {{- include "shoehorn.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "shoehorn.fullname" . }}-valkey
  namespace: {{ include "shoehorn.namespace.data" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  serviceName: {{ include "shoehorn.fullname" . }}-valkey
  replicas: {{ .Values.valkey.replicas }}
  selector:
    matchLabels:
      {{- include "shoehorn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: valkey
  template:
    metadata:
      labels:
        {{- include "shoehorn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: valkey
    spec:
      {{- include "shoehorn.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "shoehorn.serviceAccountName" . }}
      securityContext:
        {{- if .Values.valkey.podSecurityContext }}
        {{- toYaml .Values.valkey.podSecurityContext | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
      - name: valkey
        securityContext:
          {{- if .Values.valkey.securityContext }}
          {{- toYaml .Values.valkey.securityContext | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
        image: "{{ .Values.valkey.image.repository }}:{{ .Values.valkey.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: valkey
          containerPort: 6379
          protocol: TCP
        env:
        {{- include "shoehorn.secretRef" (dict "env" "VALKEY_PASSWORD" "root" .) | nindent 8 }}
        command:
          {{- toYaml .Values.valkey.command | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.valkey.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.valkey.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.valkey.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /data
      {{- if not .Values.valkey.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.valkey.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.valkey.persistence.storageClass }}
      {{- if (eq "-" .Values.valkey.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.valkey.persistence.storageClass | quote }}
      {{- end }}
      {{- else if .Values.global.storageClass }}
      storageClassName: {{ .Values.global.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.valkey.persistence.size }}
  {{- end }}
{{- end }}
