{{- if and .Values.postgresql.enabled (not .Values.postgresql.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoehorn.fullname" . }}-postgresql
  namespace: {{ include "shoehorn.namespace.data" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "shoehorn.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "shoehorn.fullname" . }}-postgresql
  namespace: {{ include "shoehorn.namespace.data" . }}
  labels:
    {{- include "shoehorn.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "shoehorn.fullname" . }}-postgresql
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      {{- include "shoehorn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "shoehorn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      {{- include "shoehorn.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "shoehorn.serviceAccountName" . }}
      securityContext:
        {{- if .Values.postgresql.podSecurityContext }}
        {{- toYaml .Values.postgresql.podSecurityContext | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
      - name: postgresql
        securityContext:
          {{- if .Values.postgresql.securityContext }}
          {{- toYaml .Values.postgresql.securityContext | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
        image: {{ include "shoehorn.componentImage" (dict "component" .Values.postgresql "Values" .Values) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.env.POSTGRES_USER | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.env.POSTGRES_DB | quote }}
        {{- include "shoehorn.secretRef" (dict "env" "POSTGRES_PASSWORD" "root" .) | nindent 8 }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        args:
        - -c
        - config_file=/etc/postgresql/custom.conf
        livenessProbe:
          {{- toYaml .Values.postgresql.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.postgresql.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: postgresql-config
          mountPath: /etc/postgresql/custom.conf
          subPath: custom.conf
          readOnly: true
        {{- if .Values.postgresql.tls.enabled }}
        - name: postgresql-certs
          mountPath: /etc/postgresql/certs
          readOnly: true
        {{- end }}
      volumes:
      {{- if not .Values.postgresql.persistence.enabled }}
      - name: data
        emptyDir: {}
      {{- end }}
      - name: postgresql-config
        configMap:
          name: {{ include "shoehorn.fullname" . }}-postgresql-config
      {{- if .Values.postgresql.tls.enabled }}
      - name: postgresql-certs
        secret:
          secretName: {{ include "shoehorn.fullname" . }}-postgresql-tls-cert
          defaultMode: 0400
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.postgresql.persistence.storageClass }}
      {{- if (eq "-" .Values.postgresql.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
      {{- end }}
      {{- else }}
      storageClassName: {{ .Values.global.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
  {{- end }}
{{- end }}
