{{- if not .Values.shoehorn.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shoehorn-agent.fullname" . }}
  labels:
    {{- include "shoehorn-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "shoehorn-agent.annotations" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.shoehorn.apiToken | required "shoehorn.apiToken is required (or set shoehorn.existingSecret)" | quote }}
  {{- if and (eq (.Values.agent.gitops.tool | default "") "argocd") .Values.agent.gitops.argocd.token }}
  argocd-token: {{ .Values.agent.gitops.argocd.token | quote }}
  {{- end }}
{{- end }}
